### PR TITLE
Extending test coverage

### PR DESCRIPTION
**Pull request by ARosenbaum98**

### CODE REVIEW

**Comment by ryanmohler172** [comment]
[34% (+0.4%) vs master 33%](http://3.91.248.52:8080/jenkins/job/Post-Service%20-%20PR/3/)

**Review by Johngh17 — APPROVED** [review]

**Comment by ryanmohler172** [comment]
[65% (+32.1%) vs master 33%](http://3.91.248.52:8080/jenkins/job/Post-Service%20-%20PR/6/)

**Comment by ryanmohler172** [comment]
[65% (+32.1%) vs master 33%](http://3.91.248.52:8080/jenkins/job/Post-Service%20-%20PR/7/)

**Comment by ryanmohler172** [comment]
[86% (+53.09%) vs master 33%](http://3.91.248.52:8080/jenkins/job/Post-Service%20-%20PR/8/)

**Comment by ryanmohler172** [comment]
[86% (+53.09%) vs master 33%](http://3.91.248.52:8080/jenkins/job/Post-Service%20-%20PR/9/)

**Pull request merged**
