### PR TITLE
Fixed PostControllerTest, and removed duplicate validation calls.

### PR DESCRIPTION
**Pull request by SamJacobsen**

### CODE REVIEW

**Review by Johngh17 — APPROVED** [review]

**Comment by ryanmohler17** [comment]
jenkins build

**Comment by ryanmohler17** [comment]
jenkins build

**Comment by ryanmohler17** [comment]
jenkins build

**Comment by ryanmohler172** [comment]
[90% (+1.09%) vs master 89%](http://3.91.248.52:8080/jenkins/job/Post-Service%20-%20PR/46/)

**Comment by ryanmohler17** [comment]
Sorry about that, my credentials broke again. @SamJacobsen this ready to be merged?

**Pull request closed without merging**
